import { Band } from '../models/band'

export const BAND: Band[] = [
    { id: 1, name: 'The Rolling Stones', description: 'The Rolling Stones, British rock group, formed in 1962, that drew on Chicago blues stylings to create a unique vision of the dark side of post-1960s counterculture. The original members were Mick Jagger, Keith Richards, Brian Jones , Bill Wyman and Charlie Watts.', link: 'https://www.youtube.com/watch?v=nrIPxlFzDi0' },
    { id: 2, name: 'Led Zepepelin', description: 'Led Zeppelin, British rock band that was extremely popular in the 1970s. Although their musical style was diverse, they came to be well known for their influence on the development of heavy metal. The members were Jimmy Page, Robert Plant , John Paul Jones and John Bonham.', link: 'https://www.youtube.com/watch?v=xbhCPt6PZIU' },
    { id: 3, name: 'Queen', description: 'Queen, British rock band whose fusion of heavy metal, glam rock, and camp theatrics made it one of the most popular groups of the 1970s. Although generally dismissed by critics, Queen crafted an elaborate blend of layered guitar work by virtuoso Brian May and overdubbed vocal harmonies enlivened by the flamboyant performance of front man and principal songwriter Freddie Mercury. The members were Freddie Mercury, Brian May, John Deacon and Roger Taylor.', link: 'https://www.youtube.com/watch?v=f4Mc-NYPHaQ' },
    { id: 4, name: 'Pink Floyd', description: 'Pink Floyd, British rock band at the forefront of 1960s psychedelia who later popularized the concept album for mass rock audiences in the 1970s. The principal members were lead guitarist Syd Barrett, bassist Roger Waters , drummer Nick Mason , keyboard player Rick Wright and guitarist David Gilmour.', link: 'https://www.youtube.com/watch?v=IXdNnw99-Ic' },
    { id: 5, name: 'Deep Purple', description: 'Deep Purple are an English rock band formed in Hertford, Hertfordshire, in 1968. They are considered to be among the pioneers of heavy metal and modern hard rock, although their musical approach has changed over the years. Deep Purple have had several line-up changes and an eight-year hiatus (1976–1984).', link: 'https://www.youtube.com/watch?v=ikGyZh0VbPQ' },
    { id: 6, name: 'AC/DC', description: 'AC/DC, Australian heavy metal band whose theatrical, high-energy shows placed them among the most popular stadium performers of the 1980s. The principal members were Angus Young,Malcolm Young, Bon Scott , Brian Johnson, Phil Rudd, and Cliff Williams.', link: 'https://www.youtube.com/watch?v=gEPmA3USJdI' },
    { id: 7, name: 'The Ramones', description: 'The Ramones, American band that influenced the rise of punk rock on both sides of the Atlantic Ocean. The original members were Joey Ramone , Johnny Ramone , Dee Dee Ramone , and Tommy Ramone.', link: 'https://www.youtube.com/watch?v=xuOnePNlOgY' },
    { id: 8, name: 'Kiss', description: 'Kiss (often stylized as KIϟϟ) is an American rock band formed in New York City in January 1973 by Paul Stanley, Gene Simmons, Peter Criss, and Ace Frehley. Well known for its members face paint and stage outfits, the group rose to prominence in the mid–late 1970s with its shocking live performances, which featured fire breathing, blood-spitting, smoking guitars, shooting rockets, levitating drum kits, and pyrotechnics. The band has gone through several lineup changes, with Stanley and Simmons being the only members to feature in every lineup.', link: 'https://www.youtube.com/watch?v=ZhIsAZO5gl0' }
]